### PR TITLE
DEV: Rename variables to avoid conflicts

### PR DESCRIPTION
**Pull request by jordanvidrine**
This fixes variable names causing error.

### CODE REVIEW

**Review by CvX — COMMENTED** [review]
Are variables the issue? I think the problem is that we seem to have broken the syntax on line 18.

**Comment by jordanvidrine** [comment]
I was advised the variables were the issue but good find on that unneeded bracket

**Comment by jordanvidrine** [comment]
> Are variables the issue? I think the problem is that we seem to have broken the syntax on line 18.

I'm traveling right now and only have my phone. Would you mind adding a commit suggestion for that?

Thanks

**Comment by CvX** [comment]
GitHub's UI won't let me, since that line is outside the scope of this PR. 😅 But I'll push a commit to this branch. 🙂

**Comment by jordanvidrine** [comment]
Lol! Thanks a bunch

**Review by CvX — APPROVED** [review]

**Pull request merged**
