### PR TITLE
DEV: Adds sorting parameter

### PR DESCRIPTION
**Pull request by Ahmedgagan**
Hi @jordanvidrine 
I have added this PR for [this](https://meta.discourse.org/t/discourse-docs-card-filter-component/187947/10?u=ahmed_gagan) feature request.

In this PR, I have added a sorting parameter to the tag_icon & category_icons component setting.

### CODE REVIEW

**Comment by jordanvidrine** [comment]
This looks good, I would add in a description to the `settings.yml` file in the appropriate area to further explain the ability to specify the order of the `category` and `tag` cards as well.

**Comment by Ahmedgagan** [comment]
Thanks for looking into the PR, will add description to the component settings which will explain the sorting parameter.

**Comment by Ahmedgagan** [comment]
Hi @jordanvidrine 
I have added the description to the setting which states that you can specify the order of the topics list. Do have a look.

**Review by jordanvidrine — APPROVED** [review]
Looks good when testing locally :+1:

**Pull request merged**
